### ISSUE TITLE
Proposed change to argument field types

### ISSUE THREAD

**Issue by NickolausDS** [globus/globus-identifiers-client#2]
@rpwagner and @kylechard were interested in this change. 

Currently, all fields need to be specified as JSON strings. For example:

```
client.create_identifier(namespace=`<namespace>`, 
    visible_to=json.dumps(['public']),
    metadata=json.dumps({'erc.who': 'Nick'})
)
```
Proposed change is the client handles formatting args, so regular python types can be used instead:
```
client.create_identifier(namespace=`<namespace>`, 
    visible_to=['public'],
    metadata={'erc.who': 'Nick'}
)
```

**Comment by jimPruyne** [comment]
I would support this change. For current CLI use, that just means that the JSON parsing needs to move up to the CLI processing layer and that then the appropriate python types can be created from them and passed in via the client.

**Comment by rpwagner** [comment]
@NickolausDS, I think what @kylechard was discussing was more like this:
```
identifier_params = {'namespace'=<namespace>, 
   'visible_to'=['public',],  'metadata'= {'erc.who': 'Nick'}}
client.create_identifier(identifier_params)
```

**Comment by rpwagner** [comment]
Is there an `identifier` class? That might be cleaner solution, with `create`, `update`, `obsolete`, etc., methods.

**Comment by jimPruyne** [comment]
An `identifier` class *might* be a reasonable idea, though that abstracts away the REST API farther than we've often done in the past. The clear first step is to get rid of all use of `_json_parse_args` from `identifiers_api.py` and where there are presently strings passed which are then parsed within the API layer, assume that the proper python types (dicts or lists are the cases) are what are being passed.

This may also facilitate actually naming the kwargs on the various calls and not just using the generic `**kwargs` everywhere.

**Comment by rpwagner** [comment]
If there's not a class already, then just having cleaner function calls is very good start. And other clients using this code can also implement their one. E.g., a Minid class.

**Comment by NickolausDS** [comment]
I wish iterable unpacking was supported on python2.7, that way keyword arguments could still be used and folks could specify args separately:

    identifier_params = {'namespace'=<namespace>, 
       'visible_to'=['public',],  'metadata'= {'erc.who': 'Nick'}}
    client.create_identifier(**identifier_params)

Given that, I'm split evenly between using keywords and passing a dict.

**Comment by NickolausDS** [comment]
Just to confirm from the discussion, did we decide to keep keyword args or pass a dict instead? 

Also, @jimPruyne I'm free to work on this if you want. Set me as 'assigned' to confirm.

**Comment by jimPruyne** [comment]
I think we said keyword args. It provides better self-documentation, and if someone does have a dict representation, they can always pass it as `**dict_val`.

**Comment by NickolausDS** [comment]
Changes to the API are above in the WIP, but I'm not quite sure the best way to go about changing over the CLI due to some arguments being complex. For example the 'checksums' argument is a list of dicts:
```
[
    {"function": "md5", "value": "foobarbaz"}, 
    {"function": "sha256", "value": "bazbazfoo"}
]
```
One possibility would be flattening the arguments, so the above might become:
`--checksum-sha256 <sha256 checksum> --checksum-md5 <md5 checksum>`

**Comment by kylechard** [comment]
I don't think we need to support very many checksum functions in the CLI so I would vote to go with what you suggest for a couple of checksum functions.

**Comment by NickolausDS** [comment]
If I were to go that route and get rid of JSON entirely, we would also need to change how lists are parsed. A simple option is to separate list items by comma. An example there would be:

`--location http://example.com,http://otherloc.example.com`

Another issue is metadata, which is an arbitrarily complex object. We could try the same thing as above and only allow a flat object of simple types. In that case, metadata could be specified as:

`--metadata-foo bar --metadata-erc.name "Malcolm Reynolds"`

I'm a bit worried these changes will bite us down the road somewhere, such as if we need to allow some items within a list to contain commas, or if we need to find ways to get more complex data into `metadata`. If we expect we need to pass more complex types in the future I think JSON would actually be easier. On the other hand, if we keep it to simple types I'm more inclined to use these newer proposed ideas to make passing arguments on the CLI simple and easy (especially for newer users).

**Comment by jimPruyne** [comment]
I think this is headed in a good direction. I'll summarize some of the ideas and thoughts:

- Adding flags that are specific to the various/few checksum functions seems like a cleaner way of handling things. I'd support that.
- The argument list option seems kinda nice, but I'm concerned with how it blends with other arguments. In particular, if there are positional arguments how does the parser know when the list associated with the flag ends and the positional arguments begin? Perhaps that doesn't actually appear in our use case, but that ambiguity somewhat bothers me. I guess the alternatives are repeating the flag as in `--location <url1> --location <url2>` or using a comma or other separator as in `--locations <url1>,<url2>`. I guess any of these are ok. Repeating the flag seems least ambiguous or error prone to me, but is the most verbose, so perhaps is considered undesirable. I would go with the repeating the flag choice, but I don't feel real strongly about it.
- For the `metadata` values, I can see three options for reading the metadata:
  - On the command line in json format as we do today
  - From a file
  - From stdin
  The aws cli at least supports the first two of these where you can use the actual json or a value like `file://` to point to a file. If we could get that level I think it would be nice. Definitely making the metadata the only json-like structure is a good idea.

So, I'll support basically whatever approach others decide upon, especially as far as the lists go, but there's my thoughts for what they're worth.

**Comment by NickolausDS** [comment]
For argparse lists, argparse seems to support both `--locations <url1> <url2>` (via adding `nargs='+'`) _and_ `--location <url1> --location <url2>` (via adding `action='append'`). From local testing, you're right about `--locations <url1> <url2>`, there can be ambiguity if a positional argument is specified directly after a flag supporting `nargs`, such as `--locations <url1> <url2> <identifier_argument>`. Argparse detects other flags specified afterwards though, so the following works: `--locations <url1> <url2> --identifier <my_ark>`.

I think I slightly tend towards `nargs` for brevity, but I'm happy with both those options. However separating by comma doesn't appear to be natively supported by argparse (Parsing at first should be easy, but I'm afraid of the corner case where some future list argument might contain a real comma). 

For metadata, I do like how the command-line approach allows users to copy-paste identifier creation commands without relying on external files. However, allowing `metadata` to be a file would shorten the command considerably and help in the cases where a user were doing a batch creation and the metadata didn't change between identifiers (I was that user not long ago!).

**Comment by NickolausDS** [comment]
I'll start on these changes tomorrow morning. For a quick recap, I'll be adding these changes:

* `--location` and `--visible-to` will both be parsed as argparse lists
* `--checksum` will become `--checksum-<algorithm>` 
* `--metadata` will continue to be JSON, but can also be specified by file `--metadata file://foo.json`

@jimPruyne For argparse lists did you still have a preference between `--locations <loc1> <loc2>` or `--location <loc1> --location <loc2>`?

**Comment by jimPruyne** [comment]
That all sounds good. I guess `--locations <loc1> <loc2>` is good. Should there be any odd reason where a location contains a space in it, that can be quoted on the command line. Only odd thing is for the common case where there's only one location, the plural is a bit weird. Should we make `--location` and `--locations` synonyms to help out with that? Then what to do we do if both are present? Merge? Probably more trouble than it is worth.

**Comment by NickolausDS** [comment]
I think supporting both `--location` and `--locations` is a bit unwieldy. I do like how `--locations` implies the argument can handle more than one, and personally I would stop at including only one argument if I only had one URL to give it (although I have never included more than one). I see how that could be confusing though, and am happy to use the other style if that doesn't appear straight forward.

I'll also add some examples to the README including some variations on commands, which should help folks along.
